// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AccountsMarginLevelResponse
    {
        /// <summary>
        /// Initializes a new instance of the AccountsMarginLevelResponse
        /// class.
        /// </summary>
        public AccountsMarginLevelResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountsMarginLevelResponse
        /// class.
        /// </summary>
        public AccountsMarginLevelResponse(System.DateTime dateTime, IList<AccountsMarginLevelContract> levels = default(IList<AccountsMarginLevelContract>))
        {
            Levels = levels;
            DateTime = dateTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "levels")]
        public IList<AccountsMarginLevelContract> Levels { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateTime")]
        public System.DateTime DateTime { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Levels != null)
            {
                foreach (var element in Levels)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
