// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountHistoryBackendRequest
    {
        /// <summary>
        /// Initializes a new instance of the AccountHistoryBackendRequest
        /// class.
        /// </summary>
        public AccountHistoryBackendRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountHistoryBackendRequest
        /// class.
        /// </summary>
        public AccountHistoryBackendRequest(string clientId = default(string), string accountId = default(string), System.DateTime? fromProperty = default(System.DateTime?), System.DateTime? to = default(System.DateTime?))
        {
            ClientId = clientId;
            AccountId = accountId;
            FromProperty = fromProperty;
            To = to;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "from")]
        public System.DateTime? FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public System.DateTime? To { get; set; }

    }
}
