// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountChargeManuallyResponse
    {
        /// <summary>
        /// Initializes a new instance of the AccountChargeManuallyResponse
        /// class.
        /// </summary>
        public AccountChargeManuallyResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountChargeManuallyResponse
        /// class.
        /// </summary>
        public AccountChargeManuallyResponse(string transactionId = default(string))
        {
            TransactionId = transactionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionId")]
        public string TransactionId { get; set; }

    }
}
