// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountChargeManuallyRequest
    {
        /// <summary>
        /// Initializes a new instance of the AccountChargeManuallyRequest
        /// class.
        /// </summary>
        public AccountChargeManuallyRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountChargeManuallyRequest
        /// class.
        /// </summary>
        public AccountChargeManuallyRequest(double amount, string clientId = default(string), string accountId = default(string), string reason = default(string))
        {
            ClientId = clientId;
            AccountId = accountId;
            Amount = amount;
            Reason = reason;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public string Reason { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
