// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AccountHistoryBackendResponse
    {
        /// <summary>
        /// Initializes a new instance of the AccountHistoryBackendResponse
        /// class.
        /// </summary>
        public AccountHistoryBackendResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountHistoryBackendResponse
        /// class.
        /// </summary>
        public AccountHistoryBackendResponse(IList<AccountHistoryBackendContract> account = default(IList<AccountHistoryBackendContract>), IList<OrderHistoryBackendContract> positionsHistory = default(IList<OrderHistoryBackendContract>), IList<OrderHistoryBackendContract> openPositions = default(IList<OrderHistoryBackendContract>))
        {
            Account = account;
            PositionsHistory = positionsHistory;
            OpenPositions = openPositions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public IList<AccountHistoryBackendContract> Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "positionsHistory")]
        public IList<OrderHistoryBackendContract> PositionsHistory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "openPositions")]
        public IList<OrderHistoryBackendContract> OpenPositions { get; set; }

    }
}
