// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountsMarginLevelContract
    {
        /// <summary>
        /// Initializes a new instance of the AccountsMarginLevelContract
        /// class.
        /// </summary>
        public AccountsMarginLevelContract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountsMarginLevelContract
        /// class.
        /// </summary>
        public AccountsMarginLevelContract(double balance, double marginLevel, int openedPositionsCount, double usedMargin, double totalBalance, string accountId = default(string), string clientId = default(string), string tradingConditionId = default(string), string baseAssetId = default(string))
        {
            AccountId = accountId;
            ClientId = clientId;
            TradingConditionId = tradingConditionId;
            BaseAssetId = baseAssetId;
            Balance = balance;
            MarginLevel = marginLevel;
            OpenedPositionsCount = openedPositionsCount;
            UsedMargin = usedMargin;
            TotalBalance = totalBalance;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tradingConditionId")]
        public string TradingConditionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baseAssetId")]
        public string BaseAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balance")]
        public double Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marginLevel")]
        public double MarginLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "openedPositionsCount")]
        public int OpenedPositionsCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usedMargin")]
        public double UsedMargin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalBalance")]
        public double TotalBalance { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
