// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountHistoryBackendContract
    {
        /// <summary>
        /// Initializes a new instance of the AccountHistoryBackendContract
        /// class.
        /// </summary>
        public AccountHistoryBackendContract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountHistoryBackendContract
        /// class.
        /// </summary>
        /// <param name="type">Possible values include: 'Deposit', 'Withdraw',
        /// 'OrderClosed', 'Reset', 'Swap', 'Manual'</param>
        public AccountHistoryBackendContract(System.DateTime date, double amount, double balance, double withdrawTransferLimit, AccountHistoryTypeContract type, string id = default(string), string accountId = default(string), string clientId = default(string), string comment = default(string), string orderId = default(string), string legalEntity = default(string), string auditLog = default(string))
        {
            Id = id;
            Date = date;
            AccountId = accountId;
            ClientId = clientId;
            Amount = amount;
            Balance = balance;
            WithdrawTransferLimit = withdrawTransferLimit;
            Comment = comment;
            Type = type;
            OrderId = orderId;
            LegalEntity = legalEntity;
            AuditLog = auditLog;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balance")]
        public double Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "withdrawTransferLimit")]
        public double WithdrawTransferLimit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Deposit', 'Withdraw',
        /// 'OrderClosed', 'Reset', 'Swap', 'Manual'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public AccountHistoryTypeContract Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "legalEntity")]
        public string LegalEntity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "auditLog")]
        public string AuditLog { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
