// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetPairBackendContract
    {
        /// <summary>
        /// Initializes a new instance of the AssetPairBackendContract class.
        /// </summary>
        public AssetPairBackendContract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetPairBackendContract class.
        /// </summary>
        public AssetPairBackendContract(int accuracy, string id = default(string), string name = default(string), string baseAssetId = default(string), string quoteAssetId = default(string))
        {
            Id = id;
            Name = name;
            BaseAssetId = baseAssetId;
            QuoteAssetId = quoteAssetId;
            Accuracy = accuracy;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baseAssetId")]
        public string BaseAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quoteAssetId")]
        public string QuoteAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accuracy")]
        public int Accuracy { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
