// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AssignInstrumentsRequest
    {
        /// <summary>
        /// Initializes a new instance of the AssignInstrumentsRequest class.
        /// </summary>
        public AssignInstrumentsRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssignInstrumentsRequest class.
        /// </summary>
        public AssignInstrumentsRequest(string tradingConditionId = default(string), string baseAssetId = default(string), IList<string> instruments = default(IList<string>))
        {
            TradingConditionId = tradingConditionId;
            BaseAssetId = baseAssetId;
            Instruments = instruments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tradingConditionId")]
        public string TradingConditionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baseAssetId")]
        public string BaseAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "instruments")]
        public IList<string> Instruments { get; set; }

    }
}
