// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ChangeOrderLimitsBackendRequest
    {
        /// <summary>
        /// Initializes a new instance of the ChangeOrderLimitsBackendRequest
        /// class.
        /// </summary>
        public ChangeOrderLimitsBackendRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ChangeOrderLimitsBackendRequest
        /// class.
        /// </summary>
        public ChangeOrderLimitsBackendRequest(string clientId = default(string), string orderId = default(string), string accountId = default(string), double? takeProfit = default(double?), double? stopLoss = default(double?), double? expectedOpenPrice = default(double?))
        {
            ClientId = clientId;
            OrderId = orderId;
            AccountId = accountId;
            TakeProfit = takeProfit;
            StopLoss = stopLoss;
            ExpectedOpenPrice = expectedOpenPrice;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "takeProfit")]
        public double? TakeProfit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stopLoss")]
        public double? StopLoss { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expectedOpenPrice")]
        public double? ExpectedOpenPrice { get; set; }

    }
}
