// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CloseAccountPositionsResult
    {
        /// <summary>
        /// Initializes a new instance of the CloseAccountPositionsResult
        /// class.
        /// </summary>
        public CloseAccountPositionsResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CloseAccountPositionsResult
        /// class.
        /// </summary>
        public CloseAccountPositionsResult(string accountId = default(string), IList<OrderFullContract> closedPositions = default(IList<OrderFullContract>), string errorMessage = default(string))
        {
            AccountId = accountId;
            ClosedPositions = closedPositions;
            ErrorMessage = errorMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "closedPositions")]
        public IList<OrderFullContract> ClosedPositions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; set; }

    }
}
