// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CloseOrderBackendRequest
    {
        /// <summary>
        /// Initializes a new instance of the CloseOrderBackendRequest class.
        /// </summary>
        public CloseOrderBackendRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CloseOrderBackendRequest class.
        /// </summary>
        public CloseOrderBackendRequest(string clientId = default(string), string orderId = default(string), string accountId = default(string))
        {
            ClientId = clientId;
            OrderId = orderId;
            AccountId = accountId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public string AccountId { get; set; }

    }
}
