// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CloseAccountPositionsResponse
    {
        /// <summary>
        /// Initializes a new instance of the CloseAccountPositionsResponse
        /// class.
        /// </summary>
        public CloseAccountPositionsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CloseAccountPositionsResponse
        /// class.
        /// </summary>
        public CloseAccountPositionsResponse(IList<CloseAccountPositionsResult> results = default(IList<CloseAccountPositionsResult>))
        {
            Results = results;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "results")]
        public IList<CloseAccountPositionsResult> Results { get; set; }

    }
}
