// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CompiledExclusionContract
    {
        /// <summary>
        /// Initializes a new instance of the CompiledExclusionContract class.
        /// </summary>
        public CompiledExclusionContract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CompiledExclusionContract class.
        /// </summary>
        public CompiledExclusionContract(System.Guid id, System.DateTime start, System.DateTime end, string assetPairRegex = default(string), string assetPairId = default(string))
        {
            Id = id;
            AssetPairRegex = assetPairRegex;
            AssetPairId = assetPairId;
            Start = start;
            End = end;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetPairRegex")]
        public string AssetPairRegex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetPairId")]
        public string AssetPairId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public System.DateTime Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "end")]
        public System.DateTime End { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
