// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CompiledExclusionsListContract
    {
        /// <summary>
        /// Initializes a new instance of the CompiledExclusionsListContract
        /// class.
        /// </summary>
        public CompiledExclusionsListContract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CompiledExclusionsListContract
        /// class.
        /// </summary>
        public CompiledExclusionsListContract(IList<CompiledExclusionContract> tradesEnabled = default(IList<CompiledExclusionContract>), IList<CompiledExclusionContract> tradesDisabled = default(IList<CompiledExclusionContract>))
        {
            TradesEnabled = tradesEnabled;
            TradesDisabled = tradesDisabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tradesEnabled")]
        public IList<CompiledExclusionContract> TradesEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tradesDisabled")]
        public IList<CompiledExclusionContract> TradesDisabled { get; set; }

    }
}
