// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DayOffExclusionInputContract
    {
        /// <summary>
        /// Initializes a new instance of the DayOffExclusionInputContract
        /// class.
        /// </summary>
        public DayOffExclusionInputContract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DayOffExclusionInputContract
        /// class.
        /// </summary>
        public DayOffExclusionInputContract(System.DateTime start, System.DateTime end, bool isTradeEnabled, string assetPairRegex = default(string))
        {
            AssetPairRegex = assetPairRegex;
            Start = start;
            End = end;
            IsTradeEnabled = isTradeEnabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetPairRegex")]
        public string AssetPairRegex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public System.DateTime Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "end")]
        public System.DateTime End { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isTradeEnabled")]
        public bool IsTradeEnabled { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
