// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class InitAccountInstrumentsBackendResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// InitAccountInstrumentsBackendResponse class.
        /// </summary>
        public InitAccountInstrumentsBackendResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// InitAccountInstrumentsBackendResponse class.
        /// </summary>
        public InitAccountInstrumentsBackendResponse(IDictionary<string, IList<AccountAssetPairModel>> accountAssets = default(IDictionary<string, IList<AccountAssetPairModel>>))
        {
            AccountAssets = accountAssets;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountAssets")]
        public IDictionary<string, IList<AccountAssetPairModel>> AccountAssets { get; set; }

    }
}
