// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InitAccountsRequest
    {
        /// <summary>
        /// Initializes a new instance of the InitAccountsRequest class.
        /// </summary>
        public InitAccountsRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InitAccountsRequest class.
        /// </summary>
        public InitAccountsRequest(string clientId = default(string), string tradingConditionsId = default(string))
        {
            ClientId = clientId;
            TradingConditionsId = tradingConditionsId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tradingConditionsId")]
        public string TradingConditionsId { get; set; }

    }
}
