// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InitAccountsResponse
    {
        /// <summary>
        /// Initializes a new instance of the InitAccountsResponse class.
        /// </summary>
        public InitAccountsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InitAccountsResponse class.
        /// </summary>
        /// <param name="status">Possible values include: 'Available',
        /// 'Created', 'Error'</param>
        public InitAccountsResponse(CreateAccountStatus status, string message = default(string))
        {
            Status = status;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Available', 'Created',
        /// 'Error'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public CreateAccountStatus Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
