// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class InitChartDataBackendResponse
    {
        /// <summary>
        /// Initializes a new instance of the InitChartDataBackendResponse
        /// class.
        /// </summary>
        public InitChartDataBackendResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InitChartDataBackendResponse
        /// class.
        /// </summary>
        public InitChartDataBackendResponse(IDictionary<string, IList<GraphBidAskPairBackendContract>> chartData = default(IDictionary<string, IList<GraphBidAskPairBackendContract>>))
        {
            ChartData = chartData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chartData")]
        public IDictionary<string, IList<GraphBidAskPairBackendContract>> ChartData { get; set; }

    }
}
