// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class InitChartDataBackendRequest
    {
        /// <summary>
        /// Initializes a new instance of the InitChartDataBackendRequest
        /// class.
        /// </summary>
        public InitChartDataBackendRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InitChartDataBackendRequest
        /// class.
        /// </summary>
        public InitChartDataBackendRequest(IList<string> assetIds = default(IList<string>), string clientId = default(string))
        {
            AssetIds = assetIds;
            ClientId = clientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetIds")]
        public IList<string> AssetIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

    }
}
