// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InstrumentBidAskPairContract
    {
        /// <summary>
        /// Initializes a new instance of the InstrumentBidAskPairContract
        /// class.
        /// </summary>
        public InstrumentBidAskPairContract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InstrumentBidAskPairContract
        /// class.
        /// </summary>
        public InstrumentBidAskPairContract(System.DateTime date, double bid, double ask, string id = default(string))
        {
            Id = id;
            Date = date;
            Bid = bid;
            Ask = ask;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bid")]
        public double Bid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ask")]
        public double Ask { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
