// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for MatchingEngineModeContract.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MatchingEngineModeContract
    {
        [EnumMember(Value = "MarketMaker")]
        MarketMaker,
        [EnumMember(Value = "Stp")]
        Stp
    }
    internal static class MatchingEngineModeContractEnumExtension
    {
        internal static string ToSerializedValue(this MatchingEngineModeContract? value)
        {
            return value == null ? null : ((MatchingEngineModeContract)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this MatchingEngineModeContract value)
        {
            switch( value )
            {
                case MatchingEngineModeContract.MarketMaker:
                    return "MarketMaker";
                case MatchingEngineModeContract.Stp:
                    return "Stp";
            }
            return null;
        }

        internal static MatchingEngineModeContract? ParseMatchingEngineModeContract(this string value)
        {
            switch( value )
            {
                case "MarketMaker":
                    return MatchingEngineModeContract.MarketMaker;
                case "Stp":
                    return MatchingEngineModeContract.Stp;
            }
            return null;
        }
    }
}
