// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MtBackendResponseString
    {
        /// <summary>
        /// Initializes a new instance of the MtBackendResponseString class.
        /// </summary>
        public MtBackendResponseString()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MtBackendResponseString class.
        /// </summary>
        public MtBackendResponseString(string result = default(string), string message = default(string))
        {
            Result = result;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "result")]
        public string Result { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
