// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MtBackendResponseMarginTradingAccountModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MtBackendResponseMarginTradingAccountModel class.
        /// </summary>
        public MtBackendResponseMarginTradingAccountModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MtBackendResponseMarginTradingAccountModel class.
        /// </summary>
        public MtBackendResponseMarginTradingAccountModel(MarginTradingAccountModel result = default(MarginTradingAccountModel), string message = default(string))
        {
            Result = result;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "result")]
        public MarginTradingAccountModel Result { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Result != null)
            {
                Result.Validate();
            }
        }
    }
}
