// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MtBackendResponseIEnumerableMarginTradingAccountModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MtBackendResponseIEnumerableMarginTradingAccountModel class.
        /// </summary>
        public MtBackendResponseIEnumerableMarginTradingAccountModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MtBackendResponseIEnumerableMarginTradingAccountModel class.
        /// </summary>
        public MtBackendResponseIEnumerableMarginTradingAccountModel(IList<MarginTradingAccountModel> result = default(IList<MarginTradingAccountModel>), string message = default(string))
        {
            Result = result;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "result")]
        public IList<MarginTradingAccountModel> Result { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
