// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderUpdateTypeContract.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderUpdateTypeContract
    {
        [EnumMember(Value = "Place")]
        Place,
        [EnumMember(Value = "Cancel")]
        Cancel,
        [EnumMember(Value = "Activate")]
        Activate,
        [EnumMember(Value = "Reject")]
        Reject,
        [EnumMember(Value = "Closing")]
        Closing,
        [EnumMember(Value = "Close")]
        Close,
        [EnumMember(Value = "ChangeOrderLimits")]
        ChangeOrderLimits
    }
    internal static class OrderUpdateTypeContractEnumExtension
    {
        internal static string ToSerializedValue(this OrderUpdateTypeContract? value)
        {
            return value == null ? null : ((OrderUpdateTypeContract)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderUpdateTypeContract value)
        {
            switch( value )
            {
                case OrderUpdateTypeContract.Place:
                    return "Place";
                case OrderUpdateTypeContract.Cancel:
                    return "Cancel";
                case OrderUpdateTypeContract.Activate:
                    return "Activate";
                case OrderUpdateTypeContract.Reject:
                    return "Reject";
                case OrderUpdateTypeContract.Closing:
                    return "Closing";
                case OrderUpdateTypeContract.Close:
                    return "Close";
                case OrderUpdateTypeContract.ChangeOrderLimits:
                    return "ChangeOrderLimits";
            }
            return null;
        }

        internal static OrderUpdateTypeContract? ParseOrderUpdateTypeContract(this string value)
        {
            switch( value )
            {
                case "Place":
                    return OrderUpdateTypeContract.Place;
                case "Cancel":
                    return OrderUpdateTypeContract.Cancel;
                case "Activate":
                    return OrderUpdateTypeContract.Activate;
                case "Reject":
                    return OrderUpdateTypeContract.Reject;
                case "Closing":
                    return OrderUpdateTypeContract.Closing;
                case "Close":
                    return OrderUpdateTypeContract.Close;
                case "ChangeOrderLimits":
                    return OrderUpdateTypeContract.ChangeOrderLimits;
            }
            return null;
        }
    }
}
