// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderDirectionContract.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderDirectionContract
    {
        [EnumMember(Value = "Buy")]
        Buy,
        [EnumMember(Value = "Sell")]
        Sell
    }
    internal static class OrderDirectionContractEnumExtension
    {
        internal static string ToSerializedValue(this OrderDirectionContract? value)
        {
            return value == null ? null : ((OrderDirectionContract)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderDirectionContract value)
        {
            switch( value )
            {
                case OrderDirectionContract.Buy:
                    return "Buy";
                case OrderDirectionContract.Sell:
                    return "Sell";
            }
            return null;
        }

        internal static OrderDirectionContract? ParseOrderDirectionContract(this string value)
        {
            switch( value )
            {
                case "Buy":
                    return OrderDirectionContract.Buy;
                case "Sell":
                    return OrderDirectionContract.Sell;
            }
            return null;
        }
    }
}
