// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderFillTypeContract.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderFillTypeContract
    {
        [EnumMember(Value = "FillOrKill")]
        FillOrKill,
        [EnumMember(Value = "PartialFill")]
        PartialFill
    }
    internal static class OrderFillTypeContractEnumExtension
    {
        internal static string ToSerializedValue(this OrderFillTypeContract? value)
        {
            return value == null ? null : ((OrderFillTypeContract)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderFillTypeContract value)
        {
            switch( value )
            {
                case OrderFillTypeContract.FillOrKill:
                    return "FillOrKill";
                case OrderFillTypeContract.PartialFill:
                    return "PartialFill";
            }
            return null;
        }

        internal static OrderFillTypeContract? ParseOrderFillTypeContract(this string value)
        {
            switch( value )
            {
                case "FillOrKill":
                    return OrderFillTypeContract.FillOrKill;
                case "PartialFill":
                    return OrderFillTypeContract.PartialFill;
            }
            return null;
        }
    }
}
