// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderDirection.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderDirection
    {
        [EnumMember(Value = "Buy")]
        Buy,
        [EnumMember(Value = "Sell")]
        Sell
    }
    internal static class OrderDirectionEnumExtension
    {
        internal static string ToSerializedValue(this OrderDirection? value)
        {
            return value == null ? null : ((OrderDirection)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderDirection value)
        {
            switch( value )
            {
                case OrderDirection.Buy:
                    return "Buy";
                case OrderDirection.Sell:
                    return "Sell";
            }
            return null;
        }

        internal static OrderDirection? ParseOrderDirection(this string value)
        {
            switch( value )
            {
                case "Buy":
                    return OrderDirection.Buy;
                case "Sell":
                    return OrderDirection.Sell;
            }
            return null;
        }
    }
}
