// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderCloseReasonContract.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderCloseReasonContract
    {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "Close")]
        Close,
        [EnumMember(Value = "StopLoss")]
        StopLoss,
        [EnumMember(Value = "TakeProfit")]
        TakeProfit,
        [EnumMember(Value = "StopOut")]
        StopOut,
        [EnumMember(Value = "Canceled")]
        Canceled,
        [EnumMember(Value = "CanceledBySystem")]
        CanceledBySystem,
        [EnumMember(Value = "ClosedByBroker")]
        ClosedByBroker
    }
    internal static class OrderCloseReasonContractEnumExtension
    {
        internal static string ToSerializedValue(this OrderCloseReasonContract? value)
        {
            return value == null ? null : ((OrderCloseReasonContract)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderCloseReasonContract value)
        {
            switch( value )
            {
                case OrderCloseReasonContract.None:
                    return "None";
                case OrderCloseReasonContract.Close:
                    return "Close";
                case OrderCloseReasonContract.StopLoss:
                    return "StopLoss";
                case OrderCloseReasonContract.TakeProfit:
                    return "TakeProfit";
                case OrderCloseReasonContract.StopOut:
                    return "StopOut";
                case OrderCloseReasonContract.Canceled:
                    return "Canceled";
                case OrderCloseReasonContract.CanceledBySystem:
                    return "CanceledBySystem";
                case OrderCloseReasonContract.ClosedByBroker:
                    return "ClosedByBroker";
            }
            return null;
        }

        internal static OrderCloseReasonContract? ParseOrderCloseReasonContract(this string value)
        {
            switch( value )
            {
                case "None":
                    return OrderCloseReasonContract.None;
                case "Close":
                    return OrderCloseReasonContract.Close;
                case "StopLoss":
                    return OrderCloseReasonContract.StopLoss;
                case "TakeProfit":
                    return OrderCloseReasonContract.TakeProfit;
                case "StopOut":
                    return OrderCloseReasonContract.StopOut;
                case "Canceled":
                    return OrderCloseReasonContract.Canceled;
                case "CanceledBySystem":
                    return OrderCloseReasonContract.CanceledBySystem;
                case "ClosedByBroker":
                    return OrderCloseReasonContract.ClosedByBroker;
            }
            return null;
        }
    }
}
