// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for PaymentType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PaymentType
    {
        [EnumMember(Value = "Transfer")]
        Transfer,
        [EnumMember(Value = "Swift")]
        Swift,
        [EnumMember(Value = "BankCard")]
        BankCard
    }
    internal static class PaymentTypeEnumExtension
    {
        internal static string ToSerializedValue(this PaymentType? value)
        {
            return value == null ? null : ((PaymentType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this PaymentType value)
        {
            switch( value )
            {
                case PaymentType.Transfer:
                    return "Transfer";
                case PaymentType.Swift:
                    return "Swift";
                case PaymentType.BankCard:
                    return "BankCard";
            }
            return null;
        }

        internal static PaymentType? ParsePaymentType(this string value)
        {
            switch( value )
            {
                case "Transfer":
                    return PaymentType.Transfer;
                case "Swift":
                    return PaymentType.Swift;
                case "BankCard":
                    return PaymentType.BankCard;
            }
            return null;
        }
    }
}
