// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ScheduleSettingsContract
    {
        /// <summary>
        /// Initializes a new instance of the ScheduleSettingsContract class.
        /// </summary>
        public ScheduleSettingsContract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ScheduleSettingsContract class.
        /// </summary>
        /// <param name="dayOffStartDay">Possible values include: 'Sunday',
        /// 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
        /// 'Saturday'</param>
        /// <param name="dayOffEndDay">Possible values include: 'Sunday',
        /// 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
        /// 'Saturday'</param>
        public ScheduleSettingsContract(DayOfWeek dayOffStartDay, string dayOffStartTime, DayOfWeek dayOffEndDay, string dayOffEndTime, string pendingOrdersCutOff, IList<string> assetPairsWithoutDayOff = default(IList<string>))
        {
            DayOffStartDay = dayOffStartDay;
            DayOffStartTime = dayOffStartTime;
            DayOffEndDay = dayOffEndDay;
            DayOffEndTime = dayOffEndTime;
            AssetPairsWithoutDayOff = assetPairsWithoutDayOff;
            PendingOrdersCutOff = pendingOrdersCutOff;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Sunday', 'Monday',
        /// 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'
        /// </summary>
        [JsonProperty(PropertyName = "dayOffStartDay")]
        public DayOfWeek DayOffStartDay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dayOffStartTime")]
        public string DayOffStartTime { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Sunday', 'Monday',
        /// 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'
        /// </summary>
        [JsonProperty(PropertyName = "dayOffEndDay")]
        public DayOfWeek DayOffEndDay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dayOffEndTime")]
        public string DayOffEndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetPairsWithoutDayOff")]
        public IList<string> AssetPairsWithoutDayOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pendingOrdersCutOff")]
        public string PendingOrdersCutOff { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DayOffStartTime == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DayOffStartTime");
            }
            if (DayOffEndTime == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DayOffEndTime");
            }
            if (PendingOrdersCutOff == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PendingOrdersCutOff");
            }
        }
    }
}
