// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SetTradingConditionModel
    {
        /// <summary>
        /// Initializes a new instance of the SetTradingConditionModel class.
        /// </summary>
        public SetTradingConditionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SetTradingConditionModel class.
        /// </summary>
        public SetTradingConditionModel(string clientId = default(string), string accountId = default(string), string tradingConditionId = default(string))
        {
            ClientId = clientId;
            AccountId = accountId;
            TradingConditionId = tradingConditionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tradingConditionId")]
        public string TradingConditionId { get; set; }

    }
}
