// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.MarginTrading.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SummaryAssetInfo
    {
        /// <summary>
        /// Initializes a new instance of the SummaryAssetInfo class.
        /// </summary>
        public SummaryAssetInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SummaryAssetInfo class.
        /// </summary>
        public SummaryAssetInfo(double volumeLong, double volumeShort, double pnL, string assetPairId = default(string))
        {
            AssetPairId = assetPairId;
            VolumeLong = volumeLong;
            VolumeShort = volumeShort;
            PnL = pnL;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetPairId")]
        public string AssetPairId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "volumeLong")]
        public double VolumeLong { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "volumeShort")]
        public double VolumeShort { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pnL")]
        public double PnL { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
